[window]
opacity = 0.7

[colors.primary]
foreground = '#e2e2e2'
background = '#0f0f0f'

[colors.normal]
black = '#4b4b4b'
red = '#de8a39'
green = '#82fe26'
yellow = '#b9ee39'
blue = '#25a0ab'
magenta = '#9d899a'
cyan = '#21ed67'
white = '#e2e2e2'

[colors.bright]
black = '#5f5f5f'
red = '#e4a561'
green = '#9bfe51'
yellow = '#c4f461'
blue = '#51bdb2'
magenta = '#b1a7a5'
cyan = '#4df17f'
white = '#fdfdfd'

[font]
size = 10.75
normal = { family = "hack", style = "Regular" }
